[package]
name = "wonder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# recommended to remove dynamic when you're ready to ship/release.
[dependencies]
bevy = { version = "0.7", feature = ["dynamic"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
